server:
  port: 8484
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: jms
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
    add-mappings: true

    spring:
      mail:
        host: smtp.gmail.com
        port: 587
        username: akstmrdlsla@gmail.com
        password: wkd268425@
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace